title: Message from the Orks
author: Saroman
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Time is an ilousion to help things make sense, 
  so we always living in the present tense. It is unforgiving when a good thing ends. But you and I will always be best friends. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
